-- WEEK 1: Snowflake Geospatial Data Loading
-- Project: Mobile Device Movement / Footfall Analysis

-- 1. Create database and schema
CREATE DATABASE IF NOT EXISTS MOBILITY_GEO_DB;

USE DATABASE MOBILITY_GEO_DB;

CREATE SCHEMA IF NOT EXISTS RAW;

USE SCHEMA RAW;


-- 2. Create raw device-ping table
CREATE OR REPLACE TABLE RAW_DEVICE_PINGS (
    DEVICE_ID VARCHAR,
    LATITUDE FLOAT,
    LONGITUDE FLOAT,
    EVENT_TIMESTAMP TIMESTAMP_NTZ,
    LOCATION GEOGRAPHY
);


-- 3. Generate mock mobile-device GPS pings
-- Approximately 100,000 records
INSERT INTO RAW_DEVICE_PINGS
    (DEVICE_ID, LATITUDE, LONGITUDE, EVENT_TIMESTAMP, LOCATION)

SELECT
    'DEVICE_' || LPAD(SEQ4()::VARCHAR, 6, '0') AS DEVICE_ID,

    12.90 + UNIFORM(0::FLOAT, 0.20::FLOAT, RANDOM()) AS LATITUDE,

    77.50 + UNIFORM(0::FLOAT, 0.20::FLOAT, RANDOM()) AS LONGITUDE,

    DATEADD(
        MINUTE,
        UNIFORM(0, 10080, RANDOM()),
        '2026-09-01 00:00:00'::TIMESTAMP_NTZ
    ) AS EVENT_TIMESTAMP,

    ST_MAKEPOINT(
        LONGITUDE,
        LATITUDE
    ) AS LOCATION

FROM TABLE(GENERATOR(ROWCOUNT => 100000));


-- 4. Check the loaded data
SELECT *
FROM RAW_DEVICE_PINGS
LIMIT 10;


-- 5. Validate total number of records
SELECT COUNT(*) AS TOTAL_PINGS
FROM RAW_DEVICE_PINGS;


-- 6. Validate the GEOGRAPHY column
SELECT
    DEVICE_ID,
    LATITUDE,
    LONGITUDE,
    EVENT_TIMESTAMP,
    LOCATION
FROM RAW_DEVICE_PINGS
LIMIT 10;